### ISSUE TITLE
【校对】问题汇总及讨论（暂时不要关闭）

### ISSUE THREAD

**Issue by stanzhai** [numbbbbb/the-swift-programming-language-in-chinese#180]
问题列表：
1. 3.7Attributes，中的声明特性下的各段落格式如何优化？记得前面的一些章节也有跟这个类似的，目前的展现形式不是特别好，需要改进。
2. ~~第三章，各小节的，语法说明，链接不匹配问题，需要在各小节添加对应的锚点（链接比较多最好不要动了，把锚点加上就OK了，这个很多比较麻烦）~~
3. ~~3.02_Lexical_Structure，关键字列表过长的问题~~

**Comment by zlphoenix** [comment]
第2.10节 属性观察器 中 overriding 翻译成重载明显不合适，应该是重写，有些地方翻译成覆盖也还说得过去
