### ISSUE TITLE
章节1.2(swift初见)中用法报错

### ISSUE THREAD

**Issue by ieiayaobb** [numbbbbb/the-swift-programming-language-in-chinese#346]
原文中

    let emptyArray = String[]()

IDE提示是用

    let emptyArray = [String]()

**Comment by numbbbbb** [comment]
现在的版本确实还没有更新到最新，如果你愿意的话可以直接参与修改 :smile:

**Comment by ieiayaobb** [comment]
我先看完它，收集一下所有的问题，可以的话很乐意参与修改

**Comment by numbbbbb** [comment]
@ieiayaobb 哈哈 那就太好了 非常感谢！
