### ISSUE TITLE
2.12翻译错误，"subscript"错误翻译成"下标脚本"应为"下标"

### ISSUE THREAD

**Issue by vitoz** [numbbbbb/the-swift-programming-language-in-chinese#349]
subscript	英['sʌbskrɪpt]
美[ˈsʌbˌskrɪpt]
adj.	下标的，写在下方的，脚注的
n.	下标，脚注，下角数码

**Comment by lurongkai** [comment]
@numbbbbb 这个issue关闭的原因是什么呢？
请参见[https://www.microsoft.com/Language/zh-cn/Search.aspx?sString=subscript&langID=zh-cn]
subscript翻译成下标脚本不容易理解，仅供参考。
