### ISSUE TITLE
18_Type_Casting 里 ‘Any和AnyObject的类型转换’ 语法错误 

### ISSUE THREAD

**Issue by leiyong316** [numbbbbb/the-swift-programming-language-in-chinese#367]
before:

let someObjects: AnyObject[] = [
    Movie(name: "2001: A Space Odyssey", director: "Stanley Kubrick"),
    Movie(name: "Moon", director: "Duncan Jones"),
    Movie(name: "Alien", director: "Ridley Scott")
]

for movie in someObjects as Movie[] {
    println("Movie: '\(movie.name)', dir. \(movie.director)")
}

－－－－－－－－－－－－－－－－－－－－－－－－－

after:

let someObjects: [AnyObject] = [
    Movie(name: "2001: A Space Odyssey", director: "Stanley Kubrick"),
    Movie(name: "Moon", director: "Duncan Jones"),
    Movie(name: "Alien", director: "Ridley Scott")
]

for movie in someObjects as [Movie] {
    println("Movie: '\(movie.name)', dir. \(movie.director)")
}

**Comment by numbbbbb** [comment]
已修改，多谢！
