### ISSUE TITLE
准备翻译2.0版本吗

### ISSUE THREAD

**Issue by calvingit** [numbbbbb/the-swift-programming-language-in-chinese#372]
如题

**Comment by daofugui** [comment]
英语水平不够怎么翻译……我也很想


发自网易邮箱大师
在2015年06月09日 22:42，Calvin Cheung 写道:

如题

**Comment by daofugui** [comment]
如果有啥需要效劳的，愿意尽自己的一份力


发自网易邮箱大师
在2015年06月09日 22:43，王金鹏 写道:
英语水平不够怎么翻译……我也很想


发自网易邮箱大师
在2015年06月09日 22:42，Calvin Cheung 写道:

如题

**Comment by Chopinsky** [comment]
如果确定开始翻译，我愿意参加！

**Comment by TheLittleBoy** [comment]
关注一下~

**Comment by longjing2000** [comment]
预先报名。。。

**Comment by DavidHu0921** [comment]
报名

**Comment by dreamkidd** [comment]
英语水平不是很好，但是想参与进来，可以么？

**Comment by yakirChen** [comment]
😀2.0~

**Comment by numbbbbb** [comment]
非常感谢大家的热情~

我了解了一下，CocoaChina那边也在组织新内容的翻译，重复翻译会浪费大家的时间，所以我们直接加入他们的翻译工作。最终翻译完毕后，我会从CocoaChina那边把译文更新过来，同时会保留译者的ID，大家的翻译结果也会同时展示在swiftguide网站和CocoaChina的官网，这样会有更多人可以受益。

感兴趣的朋友可以点击这个链接：https://github.com/CocoaChina-editors/Welcome-to-Swift/issues/123

大家有什么问题可以直接过去发issue，联系我也可以，我可以帮忙联系那边的负责人。

**Comment by numbbbbb** [comment]
大家好，刚才的信息有误，我删掉重新发一下。

官方文档的更新历史：https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/RevisionHistory.html#//apple_ref/doc/uid/TP40014097-CH40-ID459

目前官方文档还没有更新新内容，所以我们先等等。等新内容出来之后会在这里组织翻译，希望感兴趣的朋友能参与进来！

英语水平不好也没关系，只要用心就可以，新版本肯定会有一些细微的改动，这更加考验大家的细心程度，去发现文档中哪里被修改。

说实话我没想到时隔一年还有这么多朋友对翻译感兴趣，我们一起努力，保证文档能及时更新😄

**Comment by zyg-gitbut** [comment]
话说 现在的 有多久没更新  好多代码都是错误的。。。。。

**Comment by numbbbbb** [comment]
各位 可以开始认领 2.0 的翻译了：https://github.com/numbbbbb/the-swift-programming-language-in-chinese/issues/383

**Comment by zilaiyedaren** [comment]
我先关注下，等新的文档出来了，我再来认领，希望组织者给予机会！

**Comment by Alex1989Wang** [comment]
Swift2.2版本有修订么？
