### ISSUE TITLE
隐式解析可选类型  的代码有误

### ISSUE THREAD

**Issue by zyg-gitbut** [numbbbbb/the-swift-programming-language-in-chinese#378]
错误的：
if assumedString {
    println(assumedString)
}
应该改为：
if assumedString != nil {
    println(assumedString)
}

**Comment by numbbbbb** [comment]
多谢！这几天我修改一下。

**Comment by lurongkai** [comment]
Fixed with commit 25263760514582337a476df2c5d2dc7056874109.
