### ISSUE TITLE
类的可失败构造器 有代码报错

### ISSUE THREAD

**Issue by zyg-gitbut** [numbbbbb/the-swift-programming-language-in-chinese#379]
class Product {
    let name: String!
    init?(name: String) {
        if name.isEmpty { return nil }
        self.name = name
    }
}

“let name:String!”  有错

**Comment by zyg-gitbut** [comment]
应该改为
class Product {
    let name: String!
    init? ( name: String ) {
        self.name = name
        if name.isEmpty {
            return nil
        }
    }
}

**Comment by lurongkai** [comment]
fixed with commit 08a84ae4df0ebe8b46d5d3ec568879166d49beaa, please close this issue.
