### ISSUE TITLE
Swift 2.0 翻译启动

### ISSUE THREAD

**Issue by numbbbbb** [numbbbbb/the-swift-programming-language-in-chinese#383]
苹果官方的 Swift 文档已经更新到 Swift 2.0，具体的更新内容见下方链接：
https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/RevisionHistory.html#//apple_ref/doc/uid/TP40014097-CH40-ID459

由于之前的文档有些细节已经过时，所以这次同步 Swift 2.0，我们采取的方式是将所有章节都重新进行校对，将现有中文翻译和英文原文进行比对，修改不一致的地方。

**参与方式**：
- 请先查看章节列表以及本 issue 下方的回复，选择目前无人认领的章节，在本 issue 下方**回复你要认领的章节名**
- Git 相关命令参见本项目[README部分](https://github.com/numbbbbb/the-swift-programming-language-in-chinese)中**参考流程**部分，如果确实不会使用 Git，也可以直接把翻译内容发布到本项目的issue中
- 认领章节之后，进入项目的`source`文件夹，然后进入对应的章节，找到认领的章节对应的 md 文件并修改内容
- 为了方便交流，认领章节之后请加入 QQ 群：470920057，注明 GitHub ID。本群只添加参与翻译的朋友

**注意**：
- 需要使用 markdown 语法
- 因为大部分内容之前已经翻译过，这次的翻译量不会很大。但是一定要**细心**，仔细对比中文和英文的差异并进行修正
- 每个章节的认领人都可以将自己的 ID 添加到章节开始处
- 原则上不要求完成时间，不过在保证质量的情况下当然是越快越好 :)

新文档更新了一章 Error Handling，因此三章一共有 37 节内容，下面列出所有的内容，请大家在下方回复进行认领。

*章节都已完成，正在同步苹果最新的文档更新*

**认领状态（37/37） |  完成状态（37/37）**：
- About Swift （**完成** By：@xtymichael）
- A Swift Tour（**完成** By：@xtymichael）
- The Basics（**完成** By：@xtymichael）
- Basic Operators（**完成** By：@AlanMelody）
- Strings and Characters（**完成** By：@DianQK）
- Collection Types（**完成** By：@AlanMelody）
- Control Flow（**完成** By：@AlanMelody）
- Functions（**完成** By：@dreamkidd）
- Closures（**完成** By：@100mango）
- Enumerations（**完成** By：@futantan）
- Classes and Structures（**完成** By：@SkyJean）
- Properties（**完成** By：@yangsiy）
- Methods（**完成** By：@DianQK）
- Subscripts（**完成** By：@shanksyang）
- Inheritance（**完成** By：@shanksyang）
- Initialization（**完成** By：@chenmingbiao）
- Deinitialization（**完成** By：@chenmingbiao）
- Automatic Reference Counting（**完成** By：@Channe）
- Optional Chaining（**完成** By：@lyojo）
- Error Handling（**完成** By：@lyojo）
- Type Casting（**完成** By：@yangsiy）
- Nested Types（**完成** By：@SergioChan）
- Extensions（**完成** By；@shanksyang）
- Protocols（**完成** By：@futantan）
- Generics（**完成** By：@SergioChan）
- Access Control（**完成** By：@mmoaay）
- Advanced Operators（**完成** By：@buginux）
- About the Language Reference（**完成** By：@KYawn）
- Lexical Structure（**完成** By：@buginux）
- Types（**完成** By：@EudeMorgen）
- Expressions（**完成** By：@EudeMorgen）
- Statements（**完成** By：@littledogboy）
- Declarations（**完成** By：@Lenhoon）
- Attributes（**完成** By：@KYawn）
- Patterns（**完成** By：@ray16897188）
- Generic Parameters and Arguments（**完成** By：@wardenNScaiyi）
- Summary of the Grammar（**完成** By：@miaosiqi）

**Comment by xtymichael** [comment]
想认领 
About Swift
A Swift Tour
The Basics

**Comment by numbbbbb** [comment]
@xtymichael 非常感谢！第一位认领的朋友:)

**Comment by DianQK** [comment]
Strings and Characters   
Methods
OK?
下个星期考完试，虽然英语渣，但是考完试，有时间，有耐心

**Comment by numbbbbb** [comment]
@DianQK 好的，多谢！

**Comment by SkyJean** [comment]
Classes and Structures

**Comment by SkyJean** [comment]
Classes and Structures

我大学是学英语的，然而很渣。。。：），现在做IOS开发。先认领一个吧，怕时间不够，影响进度。

**Comment by AlanMelody** [comment]
- Basic Operators
- Collection Types
- Control Flow

**Comment by dreamkidd** [comment]
* Functions
先领一章，怕时间不够

**Comment by chenmingbiao** [comment]
Initialization
Deinitialization
IOS开发，在学雅思。

**Comment by numbbbbb** [comment]
@SkyJean 好，非常感谢，如果有时间可以再领~

**Comment by numbbbbb** [comment]
@AlanMelody :ok_hand:

**Comment by numbbbbb** [comment]
@dreamkidd @chenmingbiao  :ok_hand: 多谢大家~

**Comment by EudeMorgen** [comment]
Types and Expressions

某985院校在读，计科专业，研一，六级优秀。

**Comment by KYawn** [comment]
About the Language Reference 
Attributes
这两章，Ok?

**Comment by numbbbbb** [comment]
@EudeMorgen 靠谱！已标记，多谢~
@KYawn :ok_hand: 多谢！

**Comment by Channe** [comment]
认领: Automatic Reference Counting

**Comment by numbbbbb** [comment]
@Channe :ok_hand: 多谢！

**Comment by lyojo** [comment]
在杭电读CS，英语比较好，希望认领以下章节：
Automatic Reference Counting
Optional Chaining
Error Handling

**Comment by numbbbbb** [comment]
@lyojo Automatic Reference Counting 前面的朋友认领了，我给你标记上后两个吧，Error Handling 是全新的一章，需要翻译的内容较多。

**Comment by lyojo** [comment]
@numbbbbb OK

**Comment by 100mango** [comment]
认领：Closures

**Comment by numbbbbb** [comment]
@100mango :ok_hand: 多谢！

**Comment by Realank** [comment]
顶！本人英语不好，就不翻译了，但是感谢和支持大家的无私贡献和积极交流的行为

会持续关注进度，随后会帮助纠正错别字一类的，作出自己的贡献

发自我的 iPhone

**Comment by lcepy** [comment]
关注中...

**Comment by numbbbbb** [comment]
@Realank @lcepy 欢迎来挑错~~~

**Comment by futantan** [comment]
@numbbbbb 
Enumerations
Protocols
这两章，ok？

**Comment by yangsiy** [comment]
认领：
Properties
Type Casting

同级校友啊，我是21系的，支持！

**Comment by shanksyang** [comment]
认领：
Subscripts
Inheritance

**Comment by mmoaay** [comment]
Protocols

**Comment by shanksyang** [comment]
再认领：Extensions

**Comment by numbbbbb** [comment]
@futantan 已标记，多谢！

**Comment by numbbbbb** [comment]
@yangsiy 哈哈，看来是读研了？

**Comment by numbbbbb** [comment]
@shanksyang 已标记，多谢！

**Comment by numbbbbb** [comment]
@mmoaay 不好意思，上面的朋友@futantan 已经认领了这一节，再选一个吧～

**Comment by mmoaay** [comment]
access control

**Comment by yangsiy** [comment]
@numbbbbb 哈哈是的

**Comment by longjing2000** [comment]
还有没有未认领的 组织者随便丢一个给我 上次就没参加成

**Comment by Lenhoon** [comment]
第一次参加，现在研一，在学习iOS开发，感觉参加这项活动蛮有意义地，还有没认领地，给我一个就好~

**Comment by SergioChan** [comment]
认领 Nested Types和Generics 
啥也不说了 

@yangsiy 好基友，同系同级，合作伙伴

**Comment by SergioChan** [comment]
@numbbbbb Got it.Thx!

**Comment by numbbbbb** [comment]
@mmoaay 已标记，多谢！
@longjing2000 好的，分配了Advanced Operators
@SergioChan 哈哈，给力。

**Comment by ray16897188** [comment]
认领pattern吧

**Comment by longjing2000** [comment]
多谢

**Comment by numbbbbb** [comment]
@ray16897188 已标记，多谢～

**Comment by littledogboy** [comment]
认领 Statements  吧。

**Comment by numbbbbb** [comment]
@littledogboy 已标记，多谢！

**Comment by miaosiqi** [comment]
想认领Summary of the Grammar

**Comment by numbbbbb** [comment]
@miaosiqi 已标记，多谢！

**Comment by miaosiqi** [comment]
不客气，我会尽力而为






------------------ 原始邮件 ------------------
发件人: "梁杰"<notifications@github.com>; 
发送时间: 2015年6月28日(星期天) 晚上6:43
收件人: "numbbbbb/the-swift-programming-language-in-chinese"<the-swift-programming-language-in-chinese@noreply.github.com>; 
抄送: "缪斯奇"<1336225019@qq.com>; 
主题: Re: [the-swift-programming-language-in-chinese] Swift 2.0 翻译启动 (#383)




@miaosiqi 已标记，多谢！

**Comment by wardenNScaiyi** [comment]
@Generic Parameters and Arguments I will try my best = =

**Comment by Lenhoon** [comment]
今年研一，正在学习iOS，认领下Declarations，感觉还是蛮有意义的~

**Comment by wardenNScaiyi** [comment]
认领Generic Parameters and Arguments
 I will try my best = =

**Comment by buginux** [comment]
只剩三个了，啊啊啊，没得选了。刚刚看到我楼上的哥们又挑走了一个，那我就认领**Declarations**吧

**Comment by devSC** [comment]
Generic Parameters and Arguments 求认领/

**Comment by numbbbbb** [comment]
@Lenhoon @wardenNScaiyi @buginux 已标记，非常感谢！

**Comment by numbbbbb** [comment]
@devSC 很抱歉，这篇已经被前面的朋友认领了，目前所有章节都被认领完毕，可以等几天参与校对。如果有朋友无法完成认领的章节，我一定联系你，谢谢！

**Comment by athenaxing** [comment]
我也想认领呢 回头等通知哈

**Comment by numbbbbb** [comment]
完成翻译的朋友请在 QQ 群或者这里回复一下，我会及时修改状态~

**Comment by buginux** [comment]
Language Reference的第二章“Lexical Structure”已经翻译完成。

**Comment by numbbbbb** [comment]
@buginux 好的

**Comment by SergioChan** [comment]
@numbbbbb Language Guide中的Nested Type已经翻译完成。

**Comment by numbbbbb** [comment]
@SergioChan 已经提交pull request了吗？

**Comment by longjing2000** [comment]
梁，帮忙把之前分配给我的章节，重新assign给其他队友，最近完全没有时间。。。不好意思。。。。

**Comment by numbbbbb** [comment]
@longjing2000 好的

**Comment by SergioChan** [comment]
@numbbbbb 跟Generic那个pull request在一起了。。

**Comment by qinix** [comment]
@yangsiy @numbbbbb @SergioChan

一下发现了这么多北航校友，惊喜啊

**Comment by numbbbbb** [comment]
@qinix 哈哈哈哈

**Comment by athenaxing** [comment]
怎么能知道是北航校友啊 哪里有信息吗？


在2015年07月04日 01:48，Eric Zhang 写道:

@yangsiy@numbbbbb@SergioChan

一下发现了这么多北航校友，惊喜啊

**Comment by buginux** [comment]
Language Guide的第二十五章“高级运算符”已经翻译完成。

**Comment by EudeMorgen** [comment]
@numbbbbb 已发送至你的gmail邮箱

**Comment by SergioChan** [comment]
@numbbbbb Nested Type的commit和Generics放在一起提交的Pull Request,你已经通过了..Nested Type已经完成.

**Comment by TJRoger** [comment]
我來翻一下`Error Handling`吧，感觉[@lyojo](https://github.com/lyojo)工作量有点大，`Optional Chaining`还没有翻完

**Comment by lyojo** [comment]
@TJRoger 以及翻译完，校对一下就提交

**Comment by TJRoger** [comment]
@lyojo Optional Chaining校对下就可以了，Error handling 也翻完了？那我就不用再折腾了，感觉这次整个项目翻译的有点慢

**Comment by lyojo** [comment]
@TJRoger Optional Chaining感觉问题比较大，很多地方直接用中文单词代替，讲不通而且意思不对。

**Comment by TJRoger** [comment]
@lyojo 那你把Optional Chaining校对过的部分发给我吧，我来校对好了

**Comment by lyojo** [comment]
@TJRoger 主要是在Optional一词的意思上有分歧。我在别的issue里面看到你认为是“可选”，但是可选讲不通，我认为是“可空：的意思。原文的意思应该是一个链式调用：classA.classB.classC，其中classB为空(nil)的时候，调用失败，所以我觉得是可空。

**Comment by lyojo** [comment]
@TJRoger 如果按照原文作者的意思校正，很多东西都讲不通，而且原来的版本已经在网络上流传开来了，我觉得有必要重新翻译一下而不是校对。

**Comment by TJRoger** [comment]
不用纠结这个词的翻译，先把当作一个术语放那里（就用术语表里的翻译就行），把整个项目弄完

2015-07-21 17:22 GMT+08:00 lyojo <notifications@github.com>:

**Comment by TJRoger** [comment]
@lyojo 那你现在是个什么情况，Optional Chaining和Error Handling的翻译和校对状况是怎样的呢？如果有弄好的就先发布了。需要帮忙的话就直接跟我说就行

**Comment by zyg-gitbut** [comment]
快翻译完了 期待期待ing。。。

**Comment by lyojo** [comment]
@TJRoger Error Handling已经提交了，可以看下有没有不妥的地方，Optional Chaining也重新翻了一遍，校对一下就提交。

**Comment by dashgeng** [comment]
@numbbbbb The Basics（认领 By：@shanksyang）没看到shanks yang认领这一章啊，你确定没有标记错误？
@shanksyang The Basics 这一章的认领人是你吗？确认一下。如果不是，请告知 @numbbbbb 。
目前状态 36/37，一直在关注，真心着急啊～～

**Comment by zyg-gitbut** [comment]
有可能 没认领到~  The Basics 应该跟以前变化不大吧

**Comment by magicdict** [comment]
7/21 官方又更新了,打算什么时候更新中文版阿?

**Comment by Hs-Yeah** [comment]
终于完成啦~

**Comment by dashgeng** [comment]
祝贺2.0翻译完成！

**Comment by numbbbbb** [comment]
@magicdict 目前正在更新7.21的内容

@Hs-Yeah @dashgeng  更新完苹果最新的内容就发布！

**Comment by atcuan** [comment]
每天都来看看，今天终于看到翻译完了，幸苦了。

**Comment by KennyZhu** [comment]
32个赞

**Comment by numbbbbb** [comment]
@atcuan @KennyZhu  :smile: 感动啊

**Comment by transcosmos** [comment]
大家辛苦了 给大家点赞

**Comment by tyhqiushen** [comment]
辛苦啦，大神们。啥时发布啊？

**Comment by ShangChuanliang** [comment]
给大家伙64个赞！

**Comment by AllenWp** [comment]
期待发布。

**Comment by zyg-gitbut** [comment]
辛苦啦！ 期待发布~

**Comment by barbarianc** [comment]
大神们辛苦了，有发布的时间表吗？也好慢慢等啊。天天来F5,都没有动静。

**Comment by vincent4j** [comment]
@barbarianc 今天下午 四点 发布了 
http://wiki.jikexueyuan.com/project/swift/

**Comment by barbarianc** [comment]
期待已久，终于看到发布了，十万分感谢！感谢你们对这个项目的不懈坚持和努力！感谢你们为开源事业贡献了宝贵的力量！

**Comment by numbbbbb** [comment]
@barbarianc 多谢支持！！

**Comment by magicdict** [comment]
官方 8/6 又更新了...

**Comment by numbbbbb** [comment]
@magicdict 我们准备等正式版出来再统一更新，不然小更新太多。

**Comment by magicdict** [comment]
@numbbbbb  可以开始更新了，9/9版本的出来了。

**Comment by adison** [comment]
今天发现playground有一些指令过期了 Xcode Version 6.4 (6E35b) ，这部份有人认领吗？

**Comment by numbbbbb** [comment]
好的，下周就开始更新。

2015-09-10 17:24 GMT+08:00 Adison <notifications@github.com>:

> 今天发现playground有一些指令过期了 Xcode Version 6.4 (6E35b) ，这部份有人认领吗？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numbbbbb/the-swift-programming-language-in-chinese/issues/383#issuecomment-139181092>
> .
>



-- 
http://about.me/numbbbbb

**Comment by magicdict** [comment]
@numbbbbb 
最近在做Swift的教育工作，jikexueyuan的PDF文档严重更新延迟。
希望能够通知jikexueyuan网站，更加频繁的进行更新，或者你这里自己出版PDF吧。
公司环境不是每个人可以随时访问外网的，所以需要PDF文档。
错误的文档导致了很多实验无法完成，另外PDF的Unicode有些字符打不出来，Mac上是 ？
不知道能解决吗，谢谢

**Comment by numbbbbb** [comment]
我和他们沟通一下，更新问题能解决，Unicode可能是字体有问题，我问问他们是否能解决。
生成电子书的坑确实很多，如果有时间的话可以直接把项目clone下来，然后用gitbook在本地生成一套静态页面，这样就可以在内部阅读了。

在 2015年9月17日 上午11:15，MagicHu <notifications@github.com>写道：

> @numbbbbb <https://github.com/numbbbbb>
> 最近在做Swift的教育工作，jikexueyuan的PDF文档严重更新延迟。
> 希望能够通知jikexueyuan网站，更加频繁的进行更新，或者你这里自己出版PDF吧。
> 公司环境不是每个人可以随时访问外网的，所以需要PDF文档。
> 错误的文档导致了很多实验无法完成，另外PDF的Unicode有些字符打不出来，Mac上是 ？
> 不知道能解决吗，谢谢
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numbbbbb/the-swift-programming-language-in-chinese/issues/383#issuecomment-140956970>
> .
>



-- 
http://about.me/numbbbbb

**Comment by floydzhang315** [comment]
最新版的PDF已更新，请到网站页面点击离线下载获得PDF文档：http://wiki.jikexueyuan.com/project/swift/  我们会根据提交情况每周进行PDF版本的更新

**Comment by magicdict** [comment]
刚才发现了一个很低级的错误（可能是没有来得及更新，或者漏了），已经提交修改了。
官方文档已经到Swift 2.1了，你们什么时候更新阿...
我觉得你们现在需要CocoaChina这样的第三方校对志愿者了。

**Comment by numbbbbb** [comment]
正在统计改动章节，下周开始更新。第三方的校对我们非常欢迎啊，这个项目放在GitHub上就是希望有更多人一起来参与，这样才能做好。

在 2015年9月24日 上午11:01，MagicHu <notifications@github.com>写道：

> 刚才发现了一个很低级的错误（可能是没有来得及更新，或者漏了），已经提交修改了。
> 官方文档已经到Swift 2.1了，你们什么时候更新阿...
> 我觉得你们现在需要CocoaChina这样的第三方校对志愿者了。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numbbbbb/the-swift-programming-language-in-chinese/issues/383#issuecomment-142790000>
> .
>



-- 
http://about.me/numbbbbb

**Comment by zyg-github** [comment]
期待 2.1...

**Comment by HermitCarb** [comment]
@numbbbbb ，要不要考虑下出个中文版的playground。我在玩了下Swift GuidedTour.playground，感觉挺不错的，epub的优势在于注释，但是playground的优势是事实演示代码。epub里面的练习，感觉好无力呀。😀

**Comment by numbbbbb** [comment]
这个建议不错，我看下。

**Comment by HermitCarb** [comment]
@numbbbbb 其实这个挺容易做的，专门去看了看api，playground还是比较简单的。有原版的playground，加上翻译过的epub或者pdf，用Xcode替换就行了，要不我试试？

**Comment by numbbbbb** [comment]
@HermitCarb 可以啊！

**Comment by HermitCarb** [comment]
👌好的

**Comment by magicdict** [comment]
2.1什么时候开始翻译？等下一个版本出来再翻译？
能不能给个具体的时间表啊

**Comment by matthewmyu** [comment]
好棒 期待文档更新

**Comment by HermitCarb** [comment]
期待更新，不过，我在极客学院下载的epub目录好像有问题

**Comment by HermitCarb** [comment]
@numbbbbb 我发现，原先是有翻译过的playground的，简体繁体都有。但是好像是都有错误？怎么办，覆盖掉，还是？

**Comment by magicdict** [comment]
如果2.1要开始翻译的话，
第一，希望可以快速迭代，尽快让大家看到新的版本，不要等全部翻译完成才更新。
第二，在Git上新建一个2.1的分支，做为里程碑吧，少许增加一些成就感
第三，能够在翻译质量上把把关，既然选择了为大家翻译，就把这个事情做好，错误的翻译比不翻译还要糟糕
我最近已经把原本读完了，不定期的也会推一些更新给你。
加油。2.1官方版本已经推出一个月了。希望能保持一年前的热情。不忘初心。

**Comment by overtrue** [comment]
@magicdict 赞！

**Comment by barbarianc** [comment]
2.1并非是重大更新。请参考Revision History，https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/RevisionHistory.html#//apple_ref/doc/uid/TP40014097-CH40-ID459。大家平时也都有自己学业或工作要做，只要有时间一定会及时跟进参与这个项目，目前还没有专门针对这个项目的常备力量，请理解他们！

**Comment by magicdict** [comment]
2.1更新不是大问题，问题是如果使用现在的教程，部分代码在Xcode7.0.1上编译不过。
当然对于老手来说不是问题，对于新手来说够呛。
非常理解和支持这个项目的实际难处。一个建议就是等到2.1正式版出来的时候，或许就是下次官方版本更新的时候，翻译后能够进行更加严苛的校对。

**Comment by zilaiyedaren** [comment]
这是来晚了的节奏么？好像都已经认领结束咯！

**Comment by overtrue** [comment]
@numbbbbb 是否要close?

**Comment by numbbbbb** [comment]
@overtrue 好 这个确实有点误导大家

**Comment by overtrue** [comment]
@numbbbbb :laughing:
