### ISSUE TITLE
2-17有错误

### ISSUE THREAD

**Issue by yslwjj** [numbbbbb/the-swift-programming-language-in-chinese#436]
![image](https://cloud.githubusercontent.com/assets/8616761/9022352/f89c727a-38a4-11e5-9a5e-f7c00afa5670.png)

![image](https://cloud.githubusercontent.com/assets/8616761/9022372/36af7d96-38a5-11e5-85a6-0c8f129daa61.png)

如上图，跟原文有区别，而且好多内容没有采用markdown语法，我是用gitbook看的，也没有高亮，好蛋疼。。。老大们有时间就改下吧。。。辛苦了

**Comment by numbbbbb** [comment]
多谢，我会修正这里，并加上代码样式。
