### ISSUE TITLE
制作epub文件

### ISSUE THREAD

**Issue by kouliang** [numbbbbb/the-swift-programming-language-in-chinese#440]
怎样把clone到本地的资源制作成epub文件

**Comment by vincent4j** [comment]
明天直接奉上 epub 的下载地址

**Comment by iSaury** [comment]
请问会有MOBI格式的吗？

**Comment by numbbbbb** [comment]
应该是三种格式都有

**Comment by cache0928** [comment]
啥时候出epub版？

**Comment by kscorpio** [comment]
没有什么工具直接打包成pdf 的么？

**Comment by azurefang** [comment]
安装calibre
```
ln -s  /Applications/calibre.app/Contents/MacOS/ebook-convert /usr/bin
npm install gitbook -g
npm install gitbook-cli -g
git clone https://github.com/numbbbbb/the-swift-programming-language-in-chinese swift_book
cd swift_book/source
gitbook epub(pdf)
```

**Comment by strivezsh** [comment]
epub下载地址在哪里?

**Comment by zcx2001** [comment]
求pdf下载地址~~

**Comment by huang5556019** [comment]
http://pan.baidu.com/s/1mgDydeg 我做了一个急需的可以试试,如果违规,请通知我删除

**Comment by huang5556019** [comment]
干脆做了个全格式的http://pan.baidu.com/s/1i3pNKRb

**Comment by ChinaHackers** [comment]
不错。不过语法还是有问题

**Comment by Manloff** [comment]
下载地址还是1.2的。加油， 辛苦了

**Comment by MR-WXD** [comment]
epub下载地址在哪里?

**Comment by floydzhang315** [comment]
目前网站的离线下载可以下ePub(http://wiki.jikexueyuan.com/project/swift/), 不过由于兼容性问题较多，只能生成100多页。

我们修改了一部分格式错误，生成了一个过渡版本(暂时没有放到主页)，如果现在需要可以先看下这个： http://pan.baidu.com/s/1o67XON4 

最终版(无任何语法及格式错误）会在十一放假后做出来，到时候点离线下载就能看到无错的完整ePub版了。

**Comment by Manloff** [comment]
谢谢。非常期待。

**Comment by paopaosa** [comment]
现在的epub版本内容还是不全。

**Comment by CloudnuY** [comment]
貌似PDF和ePub格式的都没有语法高亮？

**Comment by wonderffee** [comment]
确实没语法高亮，试着自定义了语法高亮，网页显示正常，但是输入ePub，Mobi，PDF的代码高亮虽然有了也是显示得一塌糊涂。
相关的讨论贴：https://www.v2ex.com/t/232628

**Comment by floydzhang315** [comment]
ePub电子书生成问题已经解决，现在点击网站左下角的离线下载可以下载到完整无误的最新ePub版本电子书。另外，后面在提交内容时，请提交者检查一下文件中的代码段，代码需由<code></code>标签包裹(HTML格式)或```符号包裹(Markdown格式)，防止再次出现解析错误，影响ePub电子书的生成。

**Comment by huos3203** [comment]
> 安装calibre
> 
> ```
> ln -s  /Applications/calibre.app/Contents/MacOS/ebook-convert /usr/bin
> npm install gitbook -g
> npm install gitbook-cli -g
> git clone https://github.com/numbbbbb/the-swift-programming-language-in-chinese swift_book
> cd swift_book/source
> gitbook epub(pdf)
> ```

kindle 版本:
```
git clone the-swift-programming-language-in-chinese.git swift_book
cd swift_book/source
gitbook mobi
```
有个疑问:为什么在根目录不行,根目录的config.json生成的怎么没有章节?

**Comment by numbbbbb** [comment]
因为根目录不是 gitbook 的目录。项目里有很多其他内容，source 是简体中文的 gitbook 目录。
