### ISSUE TITLE
`构造过程`一章中`构造器的继承和重载`一节的翻译问题

### ISSUE THREAD

**Issue by WXGBridgeQ** [numbbbbb/the-swift-programming-language-in-chinese#441]
Override应翻译为重写，不应翻译为重载
有其他编程语言经验的人应该知道重写和重载的区别，这里很容易误导学习者。

**Comment by vincent4j** [comment]
overwrite 是重写

我是乔 <notifications@github.com>于2015年8月4日星期二写道：

> Override应翻译为重写，不应翻译为重载
> 有其他编程语言经验的人应该知道重写和重载的区别，这里很容易误导学习者。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numbbbbb/the-swift-programming-language-in-chinese/issues/441>
> .
>


-- 
Best Regards,
Vincent 4J <http://about.me/vincent4j>.

**Comment by WXGBridgeQ** [comment]
@vincent4j override应翻译为重写，overload才是重载

**Comment by vincent4j** [comment]
是o，你记错了

我是乔 <notifications@github.com>于2015年8月4日星期二写道：

> @vincent4j <https://github.com/vincent4j> override应翻译为重写，overload才是重载
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numbbbbb/the-swift-programming-language-in-chinese/issues/441#issuecomment-127620939>
> .
>


-- 
Best Regards,
Vincent 4J <http://about.me/vincent4j>.

**Comment by LyndonChin** [comment]
override 是**重写**父类方法
overload 是重载，方法名相同，但参数不同。

**Comment by numbbbbb** [comment]
确实是重写，已修改，多谢。
