### ISSUE TITLE
pdf 225 页，let capitalCity: City!  不对应该是 var capitalCity: City!

### ISSUE THREAD

**Issue by buoge** [numbbbbb/the-swift-programming-language-in-chinese#461]
class Country {
 let name: String
let capitalCity: City!
 init(name: String, capitalName: String) {
 self.name = name
 self.capitalCity = City(name: capitalName, country: self) 7. }
}

let capitalCity: City!  不对应该是 var capitalCity: City!

**Comment by numbbbbb** [comment]
最新版中已经修正，可以下载最新的 PDF，谢谢。
