### ISSUE TITLE
苹果貌似更新了文档.你们会有后续的补充更新吗?

### ISSUE THREAD

**Issue by RtzX** [numbbbbb/the-swift-programming-language-in-chinese#502]
在文档中, 关于可选类型的介绍中 你们是这么写的 
let possibleNumber = "123"
let convertedNumber = possibleNumber.toInt()
 但是我照着写的时候发现报错.提示我使用Int .然后 我就看了一下 英文的原版.发现确实是有变化的.
那么你们有这个打算吗?? 谢谢..

**Comment by magicdict** [comment]
一定会更新的！

**Comment by numbbbbb** [comment]
正在更新 2.1 中~

**Comment by shenyansycn** [comment]
什么时候会更新完呢？

**Comment by numbbbbb** [comment]
@shenyansycn 目前已经进入校对阶段

**Comment by magicdict** [comment]
10月20日的版本 2.1正式版，iBook已经更新了，不过苹果官网还是旧的。
@shenyansycn 
闭包 哪个章节，我把9/23的追加完了，10／20的我也会追加，这个章节的校对请等一下，谢谢。

**Comment by RtzX** [comment]
谢谢你们..没办法 英语太烂..没办法帮你们,只能默默的给你们加油了
