### ISSUE TITLE
有些代码块没有加swift代码高亮

### ISSUE THREAD

**Issue by wonderffee** [numbbbbb/the-swift-programming-language-in-chinese#519]
比如这个链接里面就很明显：https://github.com/numbbbbb/the-swift-programming-language-in-chinese/blob/gh-pages/source/chapter2/25_Advanced_Operators.md
原因是有些代码块头部是\`\`\`，而不是\`\`\`swift。
不少文件都有，得想个办法批量找到未正常匹配的\`\`\`并批量替换成\`\`\`swift

**Comment by overtrue** [comment]
刚检查已经修复了，谢谢
