### ISSUE TITLE
大家使用什么工具进行翻译，可以推荐一下吗？swift初学，想参与一下

### ISSUE THREAD

**Issue by zhangqippp** [numbbbbb/the-swift-programming-language-in-chinese#520]

**Comment by 949478479** [comment]
有道词典 - -

**Comment by dreamkidd** [comment]
google 翻译

祝工作顺利，万事如意！

Thanks & regards 

张扬
  
Mobile:   18193167599
Mail:        zhangyang911120@gmail.com

**Comment by zhangqippp** [comment]
@949478479 , @dreamkidd , 我的意思是编辑工具，比如可以分屏对照，自动查词，云保存之类的，比如windows下的trados那种，我找到一个Poedit pro，mac下的，正在试用

**Comment by dreamkidd** [comment]
我是直接分屏然后左边放Chrome,右边MacDown,直接翻译编辑就好了

祝工作顺利，万事如意！

Thanks & regards 

张扬
  
Mobile:   18193167599
Mail:        zhangyang911120@gmail.com



> 在 2015年11月2日，下午2:28，zhangqippp <notifications@github.com> 写道：
> 
> Poedit

**Comment by dreamkidd** [comment]
Hello!

 

New message, please read <http://saroptstroy.com/pardon.php?kq0>

 

124348985@qq.com
