### ISSUE TITLE
想问下source文件夹下的theme主题是怎么应用的

### ISSUE THREAD

**Issue by wonderffee** [numbbbbb/the-swift-programming-language-in-chinese#522]
我把整个工程下载到本地，用gitbook serve ./source在本地发布，代码高亮的效果与极客学院上提供的网页效果不一样，显示的应该是默认效果而不是xcode.css里面的效果，想问下是怎么设置的

**Comment by numbbbbb** [comment]
极客学院的确实不一样 他们有一套自己的样式
