### ISSUE TITLE
基础部分的数值型字面量有一处翻译有误

### ISSUE THREAD

**Issue by linwing** [numbbbbb/the-swift-programming-language-in-chinese#558]
“浮点字面量还有一个可选的指数（exponent，在十进制浮点数中通过大写或者小写的e来指定，在十六进制浮点数中通过大写或者小写的p来指定。”
英文原文（Decimal floats can also have an optional exponent, indicated by an uppercase or lowercase e; hexadecimal floats must have an exponent, indicated by an uppercase or lowercase p.）的意思是十进制浮点数的指数是可选的，十六进制浮点数的指数是必选的。
翻译里把它们两种都当作是可选的了。

**Comment by overtrue** [comment]
@linwing 感谢！

**Comment by linwing** [comment]
还有一个错误，翻译里的“浮点字面量还有一个可选的指数”，英文原文是Decimal floats，应该翻译成十进制浮点数而不是浮点字面量。
所以我觉得把现在的“浮点字面量还有一个可选的指数（exponent，在十进制浮点数中通过大写或者小写的e来指定，在十六进制浮点数中通过一个必选的大写或者小写的。” 改成 "十进制浮点数也可以有一个可选的指数，通过大写或者小写的e来指定；十六进制浮点数必须有一个指数，通过大写或者小写的p来指定" 更贴合原意一点。

**Comment by overtrue** [comment]
哦，好
