### ISSUE TITLE
已经更新到2.1但是图书封面版本号没有同步

### ISSUE THREAD

**Issue by wishsoul** [numbbbbb/the-swift-programming-language-in-chinese#560]
<img width="329" alt="2015-12-23 11 29 47" src="https://cloud.githubusercontent.com/assets/6064240/11970589/a7c520e2-a968-11e5-9002-710e53aef079.png">

**Comment by numbbbbb** [comment]
我和极客学院的人说下 多谢

**Comment by wishsoul** [comment]
u are welcome
