### ISSUE TITLE
发现了一点小问题

### ISSUE THREAD

**Issue by laipz8200** [numbbbbb/the-swift-programming-language-in-chinese#564]
中文版45页的注意：Double 精确度很高,至少有15位数字,而 Float 最少只有6位数字。选择哪个类型取决于你的代码需要处理的值的范围。
这里对应原版：“Double has a precision of at least 15 decimal digits, whereas the precision of Float can be as little as 6 decimal digits. The appropriate floating-point type to use depends on the nature and range of values you need to work with in your code. In situations where either type would be appropriate, Double is preferred.”

摘录来自: Apple Inc. “The Swift Programming Language (Swift 2.1)”。 iBooks. https://itun.es/cn/jEUH0.l
as little as 应翻译为“仅仅，只有”，翻译成“至少”容易产生误解.

**Comment by overtrue** [comment]
@laipz8200 谢谢！
