### ISSUE TITLE
建議加入'文件改版歷史'(Document Revision History)的資料

### ISSUE THREAD

**Issue by gogobook** [numbbbbb/the-swift-programming-language-in-chinese#577]
我了解其實官方文件內是不包含[文件改版歷史(]https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/RevisionHistory.html#//apple_ref/doc/uid/TP40014097-CH40-ID459)，但有時候我們會想知道有什麼東西被改了。

**Comment by numbbbbb** [comment]
好建议，我记录一下，多谢。
