### ISSUE TITLE
2.2什么时候开始翻译

### ISSUE THREAD

**Issue by yaochao** [numbbbbb/the-swift-programming-language-in-chinese#581]
2.2版本还开始吗，还是直接跳到3.0？

**Comment by numbbbbb** [comment]
其实之前已经更新到了 2.2，忘了改说明文件，我更新下，多谢提醒。

**Comment by benloong** [comment]
2.2明明没有更新啊，2章23-Generics 关于关联类型 已经弃用`typealias` 改用`associatetype`了啊

**Comment by shanksyang** [comment]
@benloong 清明节会更新到最新的2.2版本，我们正在更新哈
