### ISSUE TITLE
var Swift2.2中有改动

### ISSUE THREAD

**Issue by ryanzhuang** [numbbbbb/the-swift-programming-language-in-chinese#587]
通过在参数名前加关键字 `var` 来定义变量参数，这个用法在2.2中回出现警告，3.0中将去掉这个用法

**Comment by shanksyang** [comment]
这个语言特性点在哪里提到了？我只看到这个SE：https://github.com/apple/swift-evolution/blob/master/proposals/0003-remove-var-parameters.md
是说的一回事吗？
