### ISSUE TITLE
感谢各位辛勤的贡献，辛苦了

### ISSUE THREAD

**Issue by isunimp** [numbbbbb/the-swift-programming-language-in-chinese#606]
另外可以翻译下[《API设计指南》](https://swift.org/documentation/api-design-guidelines/)这篇文章么？非常感谢！

**Comment by changkun** [comment]
感谢提意见，现已翻译完成，但是不适合放到这个仓库里，可以供稿吗？@numbbbbb

初稿参见：[Swift API 设计指南](http://changkun.us/2016/05/11/swiftapi/)

**Comment by isunimp** [comment]
辛苦了。

**Comment by numbbbbb** [comment]
@changkun 可以啊！欢迎！

**Comment by changkun** [comment]
具体的流程在哪儿呢？@numbbbbb

**Comment by numbbbbb** [comment]
@changkun 邮件说吧。
