### ISSUE TITLE
请问Epub版有更新到最新版本吗？

### ISSUE THREAD

**Issue by wuleijun** [numbbbbb/the-swift-programming-language-in-chinese#621]
我看了
![image](https://cloud.githubusercontent.com/assets/2253198/15498634/f8eee8d0-21d2-11e6-8816-8de3fbba294f.png)，但是网页版中已有2.2的校对记录。

**Comment by wuleijun** [comment]
我比对了下，确实是同步更新，请问可以更新下Epub的版本吗？

**Comment by numbbbbb** [comment]
@floydzhang315 更新下吧。
