### ISSUE TITLE
Swift 3.0 中文翻译工作正式启动啦！！

### ISSUE THREAD

**Issue by crayygy** [numbbbbb/the-swift-programming-language-in-chinese#628]
早上起来看到已经更新了preview 版本，不知道什么时候开始翻译计划呢？想贡献一点微小的力量。

**Comment by numbbbbb** [comment]
我看文档的开头写着：

> IMPORTANT

> This documentation contains preliminary information about an API or technology in development. This information is subject to change, and software implemented according to this documentation should be tested with final operating system software.

看起来苹果对文档可能会有比较大的改动，我们再等等吧，等 3.0 文档稳定下来再一起翻译 😄 。到时候一定会发 issue 的。

**Comment by crayygy** [comment]
@numbbbbb 3.0 的改动有翻译计划嘛？ 😁😁

**Comment by overtrue** [comment]
@crayygy 楼上已经回复你了。

**Comment by crayygy** [comment]
@overtrue 好的，谢谢！

**Comment by TheLittleBoy** [comment]
目前看来 3.0文档的改动不是很大，下一次改动要等到出 Swift 3.1 ？

**Comment by Realank** [comment]
苹果发布会9.7就开了，要不要开始翻译，开会的时候就展示给大家呢？

**Comment by leibaozai** [comment]
![a7b5ee11jw1f6yo8hdf4pj20hr0ezmz8](https://cloud.githubusercontent.com/assets/12133314/18122688/2ed9bff2-6f9d-11e6-8678-136da77aa5cc.jpg)

**Comment by mylonly** [comment]
不知道是不是发布会之后正式发布3.0的正式版呢，我都把xcode的beta版卸载了，等更新了

**Comment by numbbbbb** [comment]
@mylonly 等正式版发布

**Comment by KENZO8503** [comment]
@leibaozai funny

**Comment by magicdict** [comment]
差不多可以开始3.0翻译了。发布会已经开过了，难不成等到4.0？

**Comment by shanksyang** [comment]
@magicdict 严格来说 Swift 3.0还没有正式发布，不过可以根据现有文档组织一波翻译了。周末我发起一下，大家都来认领吧。。

**Comment by shanksyang** [comment]
3.0 翻译工作正式启动啦！！
根据：https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/Swift_Programming_Language/RevisionHistory.html#//apple_ref/doc/uid/TP40014097-CH40-ID459
的更新记录，从2016-06-13开始，官方文档对3.0的更新章节如下：
Language Guide:
- Functions
- Control Flow
- Closures
- Protocols
- The Basics
- Advanced Operators

Language Reference:
- Attributes
- Statements
- Declarations
- Expressions
- Types
- Generic Parameters and Arguments

想翻译的小伙伴们，直接在这个issue中回复需要认领翻译的章节，先到先得。然后翻译好了提交pull request，我来审核和合并。谢谢！

**Comment by Realank** [comment]
Control Flow

**Comment by LanfordCai** [comment]
Closures

**Comment by chenmingbiao** [comment]
Closures

**Comment by chenmingbiao** [comment]
Protocols

**Comment by crayygy** [comment]
Functions

**Comment by chenmingjia** [comment]
Language Reference -> Patterns

**Comment by chenmingjia** [comment]
Expressions

**Comment by WhoJave** [comment]
Attributes

**Comment by chenmingjia** [comment]
Generic Parameters and Arguments

**Comment by chenmingjia** [comment]
Statements

**Comment by shanksyang** [comment]
苹果把2.2到3.0的revision history合并到了一起，大家都看看各自负责部分是否有更新：https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/RevisionHistory.html#//apple_ref/doc/uid/TP40014097-CH40-ID459
辛苦了。

**Comment by mmoaay** [comment]
Advanced Operators

**Comment by jerossh** [comment]
一出来的时候就打算学了，到现在还没学，哈哈

**Comment by chenmingjia** [comment]
Declarations

**Comment by MiMoIos** [comment]
现在翻译的怎么样啦!有你们,国内的开发才得以越来越好!非常的感谢!

**Comment by WhoJave** [comment]
校对修改中

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.12.43&pv=9.3.2&source=email_footer_2]
On 周日, 9月 18, 2016 at 3:44 下午, Arthur_Xp <notifications@github.com> wrote:
现在翻译的怎么样啦!有你们,国内的开发才得以越来越好!非常的感谢!

**Comment by jerossh** [comment]
swift啥时候能稳定啊，一年一个大版本。。。受不了

**Comment by Guodadada** [comment]
swift 3 英文版在iBook 下载不了，有什么渠道下载吗

**Comment by WhoJave** [comment]
@Guodadada 可以再IBookstore下载 我在香港iBookStore下载的..

**Comment by Guodadada** [comment]
我也想加入翻译组..不知道晚不晚

**Comment by LanfordCai** [comment]
Types

**Comment by lettleprince** [comment]
Types

**Comment by shanksyang** [comment]
@Guodadada 不晚，可以微信联系我一下：huiyang

**Comment by magicdict** [comment]
@WhoJave  能否提供一个副本

**Comment by crayygy** [comment]
@magicdict 
FYI.
https://www.dropbox.com/s/2ay2tt2yd2ewugz/TheSwiftProgrammingLanguage%28Swift3%29.epub?dl=0

**Comment by lettleprince** [comment]
@shanksyang 香克斯，我也添加你wx了。

**Comment by calvingit** [comment]
下载epub没那么麻烦啊，在[swift.org](https://swift.org/documentation/)里面有，[点这里](https://swift.org/documentation/TheSwiftProgrammingLanguage(Swift3).epub)下载最新的

**Comment by Drshu** [comment]
请问大概多久能翻译完毕呢？两周一个新语言真是受不了，不知道2.3到3有什么详细的改变。。

**Comment by WhoJave** [comment]
@magicdict 抱歉,这两天忙没上,上面已有朋友提供了😄 下次可以私我邮箱哈

**Comment by shanksyang** [comment]
已经发布：https://github.com/numbbbbb/the-swift-programming-language-in-chinese/releases/tag/V3.0

**Comment by bravekingzhang** [comment]
swift语言的是我见过的最搓逼的语言，但不可否认，比较好用但难“维护”
