### ISSUE TITLE
我想借用一下本翻译的内容

### ISSUE THREAD

**Issue by ice1000** [numbbbbb/the-swift-programming-language-in-chinese#630]
我在做一个学编程用的Android App，希望搬运一些本翻译的内容。

App在[这里](https://github.com/ice1000/PlasticApp)

出处的话，目前会注明在README里面，以后会在App内部说明。

可以吗？

**Comment by numbbbbb** [comment]
可以

2016-07-07 9:05 GMT+08:00 狰狞的千里冰封 <notifications@github.com>:

> 我在做一个学编程用的Android App，希望搬运一些本翻译的内容。
>
> App在这里 <https://github.com/ice1000/PlasticApp>
>
> 出处的话，目前会注明在README里面，以后会在App内部说明。
>
> 可以吗？
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/numbbbbb/the-swift-programming-language-in-chinese/issues/630>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACdCu9EqupM9NNmL7DMhLP93RHMUBlZZks5qTFDLgaJpZM4JGpXS>
> .
>



-- 
https://github.com/numbbbbb

**Comment by ice1000** [comment]
thx :+1:
