### ISSUE TITLE
swift3.0 的更新

### ISSUE THREAD

**Issue by zhuohongxiao** [numbbbbb/the-swift-programming-language-in-chinese#642]
swift 3.0 什么时候更新。

https://www.cnswift.org  说已经进行了同步更新。  但是质量。和博客的内容不怎么样。

希望将你这个开源项目持续更新。

**Comment by chenmingbiao** [comment]
请看 https://github.com/numbbbbb/the-swift-programming-language-in-chinese/issues/628，翻译工作正在进行中。

**Comment by zhuohongxiao** [comment]
谢谢！
