### ISSUE TITLE
"错误处理"一节中

### ISSUE THREAD

**Issue by jiayoufang** [numbbbbb/the-swift-programming-language-in-chinese#659]
Swift3.0     'ErrorType' has been renamed to 'Error'

**Comment by yinchaoyu** [comment]
请问怎样自己生成pdf文档？








------------------ 原始邮件 ------------------
发件人: "jiayoufang";<notifications@github.com>;
发送时间: 2016年9月23日(星期五) 下午4:09
收件人: "numbbbbb/the-swift-programming-language-in-chinese"<the-swift-programming-language-in-chinese@noreply.github.com>; 

主题: [numbbbbb/the-swift-programming-language-in-chinese] "错误处理"一节中 (#659)




Swift3.0     'ErrorType' has been renamed to 'Error'

**Comment by shanksyang** [comment]
已修复

**Comment by shanksyang** [comment]
@yinchaoyu 等下周全部校对完毕以后，生成一份放到github上
