### ISSUE TITLE
网站打不开

### ISSUE THREAD

**Issue by inkCrazy** [numbbbbb/the-swift-programming-language-in-chinese#660]
http://gg.swiftguide.cn这个网站怎么弄都开不开，奇怪了，你们都行吗。

**Comment by shanksyang** [comment]
可以打开呀，跳转估计有点慢

**Comment by inkCrazy** [comment]
我用手机，和电脑都打不开。


------------------ 原始邮件 ------------------
发件人: "shanks";<notifications@github.com>;
发送时间: 2016年9月23日(星期五) 晚上11:14
收件人: "numbbbbb/the-swift-programming-language-in-chinese"<the-swift-programming-language-in-chinese@noreply.github.com>; 
抄送: "宝强"<1264140955@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [numbbbbb/the-swift-programming-language-in-chinese] 网站打不开 (#660)




可以打开呀，跳转估计有点慢
