### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by jiayoufang** [numbbbbb/the-swift-programming-language-in-chinese#661]
在可选绑定一节中
原文描述未：
>If any of the values in the optional bindings are nil or any Boolean condition evaluates to false, the whole if statement’s condition is considered to be false. 
原翻译
>如果所有可选绑定的值为 nil 或者所有布尔条件语句都为 false ，这样整个 if 条件判断都是为 false
 
应翻译为：只要有任意一个可选绑定的值为nil，或者任意一个布尔条件未false，则整个if条件判断为false。
已代码验证过，请验证下

**Comment by shanksyang** [comment]
谢谢指正，已修改
