### ISSUE TITLE
枚举的代码有误

### ISSUE THREAD

**Issue by zhuohongxiao** [numbbbbb/the-swift-programming-language-in-chinese#662]
在 swift 初见， 语法的枚举章节。 枚举的 case 是小写开头的。

官网的：
```swift
enum CompassPoint {
    case north
    case south
    case east
    case west
}
```

翻译版本的：
```swift
enum CompassPoint {
    case North
    case South
    case East
    case West
}
```

这次更新的有点糙。

**Comment by shanksyang** [comment]
跟protocol一章的问题一样，这次苹果的更新说明没有涉及到枚举一章的修改，所以没有单独去校对这一样。我们安排翻译一下这一章。

**Comment by zhuohongxiao** [comment]
建议将所有的章节都过一遍。

**Comment by shanksyang** [comment]
枚举一章已更新

**Comment by zhuohongxiao** [comment]
我看了一下，发现没有跟新啊。   枚举代码这个问题在所有的章节中只要存在枚举代码就有这个问题

**Comment by WormZh** [comment]
确实没有更新，好几个章节都还是2.2版本的

**Comment by chenmingbiao** [comment]
@WormZh 我们是按照官方文档更新说明来进行校对的，可能有些章节的修改官方并未标注出来，这几天我们将进行全面的校对，多谢关注，如有不便敬请原谅哈。
