### ISSUE TITLE
Swift3.0变化

### ISSUE THREAD

**Issue by jiayoufang** [numbbbbb/the-swift-programming-language-in-chinese#663]
在数组遍历一节中，获取数据项的值和索引值的方法名改变，由`enumerate()`变为`enumerated()`
Swift2.1原文描述

> If you need the integer index of each item as well as its value, use the enumerate() method to iterate over the array instead. 

Swift3.0原文描述

> If you need the integer index of each item as well as its value, use the enumerated() method to iterate over the array instead.

**Comment by terry1119** [comment]
是这样的 我也发现了同样的问题
'enumerate()' has been renamed to 'enumerated()'

**Comment by shanksyang** [comment]
已经修改完成
