### ISSUE TITLE
发现几个函数名未更新,与官方不一致

### ISSUE THREAD

**Issue by qq73666** [numbbbbb/the-swift-programming-language-in-chinese#664]
![image](https://cloud.githubusercontent.com/assets/12324373/18821869/a5b9469e-83dc-11e6-9fb7-646cb242a44f.png)

**Comment by WormZh** [comment]
借个地方提一下，枚举、错误处理的那几个章节并没有更新到3.0版本的，都还是在2.2版本

**Comment by shanksyang** [comment]
@WormZh 已经改好了，上周已经修改了。只是极客那边还没有更新，现在更新了。

**Comment by WormZh** [comment]
@shanksyang 谢谢
