### ISSUE TITLE
3.0中的一些问题

### ISSUE THREAD

**Issue by DarielChen** [numbbbbb/the-swift-programming-language-in-chinese#667]
最近在整理[Swift3.0语法速查手册](https://darielchen.github.io/SwiftManual/)的时候参考了下中文版发现了一些问题.
1. P61页, 浮点数的求余计算,3.0中已经不支持了
2. P84页,创建一个带有默认值的数组的方法变掉了,应该是`var threeDouble = [Double](repeating: 0.0, count: 3)`
3. P91页,求两个集合的非公共元素的方法变掉了,`oddDigits.symmetricDifference(singleDigitPrimeNumbers).sorted()`
4. P96页,将字典中所有的key和value组成一个集合的方法错误.`let airportCodes = [String]``(airports.keys) let airportNames = [String](airports.values)`

**Comment by shanksyang** [comment]
谢谢指正，我们check并修复一下。

**Comment by DarielChen** [comment]
P168页的`方法的局部参数名称和外部参数名称`和P169页的`修改方法的外部参数名称`两个小节在3.0中去掉了

**Comment by DarielChen** [comment]
P171页的代码部分,缺少`.`
```swift
enum TriStateSwitch {
    case Off, Low, High
    mutating func next() {
        switch self {
        case .Off:
            self = .Low
        case .Low:
            self = .High
        case .High:
            self = .Off
        }
    }
}
```

**Comment by DarielChen** [comment]
P176页,下标选项,数组中创建多个相同元素的方法变了.
`grid = Array(repeating: 0.0, count: rows * columns)`

**Comment by shanksyang** [comment]
@DarielChen 你是在哪里看到的？我又重新校对了一遍，不过跟你的页数好像对不上。

**Comment by DarielChen** [comment]
http://wiki.jikexueyuan.com/project/swift/  虽然又更新了一个版本,但有些问题还在

**Comment by shanksyang** [comment]
@DarielChen 你是看的pdf？

**Comment by DarielChen** [comment]
对啊

**Comment by shanksyang** [comment]
好的，pdf随后会更新，我先检查下你提的问题在网页中是否更新：
P61页, 浮点数的求余计算,3.0中已经不支持了 已修改
P84页,创建一个带有默认值的数组的方法变掉了,应该是var threeDouble = [Double](repeating: 0.0, count: 3) 原文是：var threeDoubles = Array(repeating: 0.0, count: 3)
P91页,求两个集合的非公共元素的方法变掉了,oddDigits.symmetricDifference(singleDigitPrimeNumbers).sorted() 已修改
P96页,将字典中所有的key和value组成一个集合的方法错误.let airportCodes = [String]``(airports.keys) let airportNames = [String](airports.values) 已修改

P168页的方法的局部参数名称和外部参数名称和P169页的修改方法的外部参数名称两个小节在3.0中去掉了 已修改

P171页的代码部分,缺少. 已修改

P176页,下标选项,数组中创建多个相同元素的方法变了. 已修改

**Comment by DarielChen** [comment]
其实最主要还是示例代码的问题,后面还有不少,有些我没有记录下来,建议把示例代码都校对一遍.
比如:P274,泛型函数,应该是这样的`func swapTwoValues<T>(a: inout T, _ b: inout T)`

**Comment by shanksyang** [comment]
@DarielChen 我上周末全文都审核了一遍，建议你看最新的网页，你说的P274问题，原文是：func swapTwoValues<T>(_ a: inout T, _ b: inout T)

**Comment by DarielChen** [comment]
哦啊, 我是中英文对照着看的,`func swapTwoValues<T>(_ a: inout T, _ b: inout T)` 不指定占位类型T都通不过编译的.

**Comment by DarielChen** [comment]
你们SwiftGG翻译组还招人不,要不稍个我啊.😊

**Comment by shanksyang** [comment]
招啊，加我微信，@huiyang
