### ISSUE TITLE
函数 章节  指定参数标签 错误

### ISSUE THREAD

**Issue by Creatisan** [numbbbbb/the-swift-programming-language-in-chinese#701]
原翻译是：
你可以在**函数名称**前指定它的参数标签，中间以空格分隔：

我觉得应该是：
你可以在**参数名称**前指定它的参数标签，中间以空格分隔：

PS：说点与错误无关的，参数标签，我觉得这东西反倒影响代码的可阅读性，看一个函数，脑子里得反应一堆东西。

**Comment by overtrue** [comment]
感谢！
