### ISSUE TITLE
Swift4的官方英文文档苹果还没有更新吧？

### ISSUE THREAD

**Issue by Hstripe** [numbbbbb/the-swift-programming-language-in-chinese#704]

**Comment by magicdict** [comment]
更新了啊。6月5日。

**Comment by Hstripe** [comment]
看到了

**Comment by donly** [comment]
传送门 [The Swift Programming Language (Swift 4): About Swift](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/index.html)

**Comment by larny** [comment]
关注一下revision history

**Comment by Endhall** [comment]
挺好的

**Comment by TheLittleBoy** [comment]
啥时候开始4.0的翻译？

**Comment by bqlin** [comment]
期待

**Comment by magicdict** [comment]
@bqlin 一部分我已经翻译好了

**Comment by shanksyang** [comment]
Swift 4.0 已经正式release了，今天发我起一下4.0文档的翻译项目
