### ISSUE TITLE
麻烦放置原版电子档

### ISSUE THREAD

**Issue by ArthurXu424** [numbbbbb/the-swift-programming-language-in-chinese#710]
对于英文比较弱一点的, 看中文可能比较习惯, 英文比较强的,直接就去英文了, 就怕像我这种夹生子,如果有中英文对比,我觉得对我这种的帮助会更大,希望作者考虑我的建议
另外 using Cocoa with swift and objective-c里面还没有翻译任何东西,不知道是什么情况.

**Comment by TheLittleBoy** [comment]
README.md  第三行就是英文文档入口。
