### ISSUE TITLE
  "Swift 教程" 内存安全:  (chapter2/24_Memory_Safe.md)  列表中没有

### ISSUE THREAD

**Issue by LodgeChen** [numbbbbb/the-swift-programming-language-in-chinese#767]
需要在 the-swift-programming-language-in-chinese-gh-pages\source\SUMMARY.md中
添加:
 * [内存安全]  (chapter2/24_Memory_Safe.md)

**Comment by Mylittleswift** [comment]
已纠正，请确认。
