### ISSUE TITLE
访问不了中文版swift编程教程

### ISSUE THREAD

**Issue by shawn736** [numbbbbb/the-swift-programming-language-in-chinese#784]
https://www.cnswift.org/ 这个地址打不开，持续好几天了，2018/6/13

**Comment by numbbbbb** [comment]
我这倒是没问题，可能是网比较慢？

**Comment by shawn736** [comment]
2018/06/15 今天可以了。中文翻译的很用心，官方英文教程有些很难理解，对照着看帮助很大，谢谢
